import Navbar from "@/components/Navbar";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { getProfile, getWorks } from "@/sanity/sanity-utils";
import { PortableText } from "@portabletext/react";
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'somanyu | works',
    description: 'Generated by create next app',
}

export default async function Work() {

    const works = await getWorks();
    const profile = await getProfile();

    return (
        <>
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-10">
                <div className="md:w-1/2 w-4/5 m-auto my-28">
                    <Navbar />

                    <div className="space-y-1">
                        <h4 className="text-xl font-medium leading-none">Work</h4>
                        <p className="text-sm text-muted-foreground">
                            Tech companies: Where bugs pay rent.
                        </p>
                    </div>

                    <Separator className="my-4" />

                    <p className="mb-10">
                        I&apos;m like the tech wizard in our company, 
                        the one who turns caffeine into code. My desk is 
                        a jungle of cables, and my keyboard has more 
                        personality than my cat. When I&apos;m not 
                        battling bugs, I&apos;m waging war against the 
                        coffee machine. You can find me in meetings nodding 
                        like I understand quantum physics, but secretly 
                        thinking about ordering pizza.
                    </p>

                    <div className="flex gap-3">
                        <a className="bg-blue-500 hover:bg-blue-400 text-white font-bold py-2 px-4 border-b-4 border-blue-700 hover:border-blue-500 rounded" href={`${profile.resume}`} target="blank" rel="noopener noreferrer">View Resume</a>
                        <a className="bg-green-500 hover:bg-green-400 text-white font-bold py-2 px-4 border-b-4 border-green-700 hover:border-green-500 rounded" href={`mailto:${profile.email}`} target="blank" rel="noopener noreferrer">My Email</a>
                    </div>

                    <div className="mt-10">
                        {works.map((work) => (
                            <Card key={work._id} className="mb-4 dark:bg-zinc-900 bg-inherit dark:group-hover:bg-zinc-800 backdrop-blur-2xl border-slate-400 dark:border-input">
                                <CardHeader>
                                    <CardTitle>{work.company} - {work.role}</CardTitle>
                                    <CardDescription>{work.start} - {work.end}</CardDescription>
                                </CardHeader>
                                <CardContent>
                                    <PortableText value={work.content} />
                                </CardContent>
                            </Card>
                        ))}
                    </div>

                </div>
            </div>
        </>
    )
}