import Navbar from "@/components/Navbar";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { getProjects } from "@/sanity/sanity-utils";
import type { Metadata } from 'next';
import Link from "next/link";
import { RxExternalLink } from "react-icons/rx";

export const metadata: Metadata = {
    title: 'somanyu | projects',
    description: 'Generated by create next app',
}


export default async function Project() {

    const projects = await getProjects();

    return (
        <>
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-10">
                <div className="md:w-1/2 w-4/5 m-auto my-28">
                    <Navbar />

                    <div className="space-y-1">
                        <h4 className="text-xl font-medium leading-none">Projects</h4>
                        <p className="text-sm text-muted-foreground">
                            90% done, still debugging...
                        </p>
                    </div>

                    <Separator className="my-4" />

                    <p className="mb-10">
                        I&apos;m on a tech adventure, creating projects that 
                        are like my personal innovation playground! It&apos;s 
                        a wild ride of learning and laughter – the only bugs 
                        here are in my code, not the picnic kind.
                    </p>

                    {/* <div className="grid grid-cols-5 gap-3">
                        <Button variant="outline">
                            <FaPython className="mr-2 h-4 w-4" /> Python
                        </Button>
                        <Button variant="outline">
                            <FaReact className="mr-2 h-4 w-4" /> React
                        </Button>
                        <Button variant="outline">
                            <SiNextdotjs className="mr-2 h-4 w-4" /> NextJS
                        </Button>
                        <Button variant="outline">
                            <FaLaravel className="mr-2 h-4 w-4" /> Laravel
                        </Button>
                        <Button variant="outline">
                            <SiTailwindcss className="mr-2 h-4 w-4" /> Tailwind
                        </Button>
                    </div> */}

                    <ul className="mt-4 space-y-2">

                        {projects.map((project) => (
                            <li key={project._id}>
                                <Link href={`/projects/${project.slug}`} className="group">
                                    <Card className="dark:bg-zinc-900 bg-inherit dark:group-hover:bg-zinc-800 backdrop-blur-2xl border-slate-400 dark:border-input">
                                        <CardHeader className="pt-4 pb-2">
                                            <CardTitle className="flex gap-3">
                                                {project.name}
                                                <RxExternalLink className="block md:hidden md:group-hover:block" />
                                            </CardTitle>
                                        </CardHeader>
                                        <CardContent className="pb-3 pt-0">
                                            <CardDescription>
                                                {project.headline}
                                            </CardDescription>
                                        </CardContent>
                                    </Card>
                                </Link>
                            </li>
                        ))}
                    </ul>
                </div>
            </div>
        </>
    )
}
