import { ThemeProvider } from '@/components/theme-provider'
import { ModeToggle } from '@/components/theme-toggle'
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'
import Link from 'next/link'
import './globals.css'

const manrope = Manrope({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'somanyu | portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={manrope.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="fixed right-6 top-6 group">
            <ModeToggle />
          </div>
          <div className="fixed left-6 top-6 group">
            <Link href={'/'}>
              <Avatar>
                <AvatarImage src="https://api.dicebear.com/7.x/lorelei/svg?seed=somanyu&eyes=variant02&hair=variant07&head=variant04&mouth=happy05&nose=variant01" />
                <AvatarFallback>SS</AvatarFallback>
              </Avatar>
            </Link>
          </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
