import Navbar from "@/components/Navbar";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { getTips } from "@/sanity/sanity-utils";
import type { Metadata } from 'next';
import Link from "next/link";
import { RxExternalLink } from "react-icons/rx";

export const metadata: Metadata = {
    title: 'somanyu | tech tips',
    description: 'Generated by create next app',
}

export default async function Tips() {

    const tips = await getTips();

    return (
        <>
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-10">
                <div className="md:w-1/2 w-4/5 m-auto my-28">
                    <Navbar />

                    <div className="space-y-1">
                        <h4 className="text-xl font-medium leading-none">Tech tips</h4>
                        <p className="text-sm text-muted-foreground">
                            Tech tip: Turn it off and on.
                        </p>
                    </div>

                    <Separator className="my-4" />

                    <p className="mb-10">
                        If your computer is slower than a snail 
                        on a coffee break, don&apos;t blame the snail. 
                        Close those 37 browser tabs you opened just to 
                        watch cute cat videos. Also, remember, 
                        &quot;Ctrl+Alt+Delete&quot; is not a magic spell; 
                        it&apos;s your lifeline when things go wonky. So, 
                        save the wands for wizards, my friend! <strong>#TechTips101</strong>
                    </p>

                    <ul className="mt-4 space-y-2">

                        {tips.map((tip) => (
                            <li key={tip._id}>
                                <Link href={`/tips/${tip.slug}`} className="group">
                                    <Card className="dark:bg-zinc-900 bg-inherit dark:group-hover:bg-zinc-800 backdrop-blur-2xl border-slate-400 dark:border-input">
                                        <CardHeader className="pt-4 pb-2">
                                            <CardTitle className="flex gap-3">
                                                {tip.title}
                                                <RxExternalLink className="block md:hidden md:group-hover:block" />
                                            </CardTitle>
                                        </CardHeader>
                                        <CardContent className="pb-3 pt-0">
                                            <CardDescription>
                                                {tip.headline}
                                            </CardDescription>
                                        </CardContent>
                                    </Card>
                                </Link>
                            </li>
                        ))}
                    </ul>
                </div>
            </div>
        </>
    )
}